#!/bin/bash
chmod 400 ttwebsite.pem
ssh -i ttwebsite.pem ec2-user@"$DOMAIN" 'cd ttFlask; git pull; git reset --hard origin/master; kill $(pgrep -of app.py); nohup python3 app.py 1>/dev/null 2>/dev/null &' 
